server:
  compression:
    enabled: true
  port: 8081
  servlet:
    context-path: /client

logging:
  level:
    br.com.valandro: INFO
    org.springframework.boot: INFO

pass:
  key-store: 4rfv5tgb
  trust-store: 4rfv5tgb